name: Retrain AQI Model

on:
  schedule:
    - cron: "30 */6 * * *"  # every 6 hours (after new data)
  workflow_dispatch:  # allow manual trigger

jobs:
  train-model:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - run: |
          pip install -r requirements.txt
          pip install "hopsworks[python]==4.2.*" xgboost scikit-learn pandas
      - env:
          HOPSWORKS_API_KEY: ${{ secrets.HOPSWORKS_API_KEY }}
        run: python scripts/model_training.py
