name: Retrain AQI Models
on:
  schedule:
    - cron: "45 */6 * * *"
  workflow_dispatch:
jobs:
  train-model:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install "hopsworks[python]==4.2.*" xgboost scikit-learn pandas joblib
      - env:
          HOPSWORKS_API_KEY: ${{ secrets.HOPSWORKS_API_KEY }}
        run: python scripts/model_loading.py
